services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    tty: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - TOKEN_SECRET_KEY=secret
      - BUCKET_NAME=video-service
      - AWS_PROFILE=minio
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_ENDPOINT_URL=http://minio:9000
      - AWS_S3_FORCE_PATH_STYLE=true
      - IMAGE_URL=http://localhost:9000/video
      - TZ=Asia/Tokyo
    # restart: always
    command: air -c .air.toml