FROM golang:latest

WORKDIR /app
ENV LD_LIBRARY_PATH=/usr/local/lib

RUN go install github.com/cosmtrek/air@latest

ENV GOCACHE=/tmp/.cache
COPY go.mod go.sum ./
RUN go mod download

CMD ["/bin/bash"]